test_log.py:28 (main) DEBUG: lol 5 hey 
